version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - depguard
    - exhaustruct
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - wrapcheck
    - wsl
    - noinlineerr
  settings:
    varnamelen:
      min-name-length: 1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        path: handler
      - linters:
          - funlen
        path: _test\.go
    paths:
      - pkg
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - pkg
      - third_party$
      - builtin$
      - examples$
