run:
  timeout: 10m
linters-settings:
  varnamelen:
    min-name-length: 1
linters:
  enable-all: true
  disable:
    - wrapcheck # disable because the large amount of correspondence
    - exhaustruct # disable because unnecessary field declaration
    - rowserrcheck # disable because because of generics
    - sqlclosecheck # disable because because of generics
    - wastedassign # disable because because of generics
    - contextcheck # https://github.com/golangci/golangci-lint/issues/3711
    - depguard # disable because know how to use it
    # deprecated
    - execinquery # deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.  
    - gomnd # deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd.
    - exportloopref # deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
issues:
  exclude-dirs:
    - pkg
  exclude-rules:
    - path: handler
      linters:
        - funlen
    - path: _test\.go
      linters:
        - funlen
