name: auto update go version
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    branches:
      - main
    types:
      - opened
defaults:
  run:
    shell: bash
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.head_ref == 'renovate/go-1.x' || github.head_ref == 'renovate/golang-1.x' }}
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        with:
          app-id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Auto merge
        uses: otakakot/github-actions/composite/auto-merge@main
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
