name: test integration
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test.integration.yaml
      - "**/*.go"
      - go.mod
      - go.sum
defaults:
  run:
    shell: bash
jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod
      - name: Test integration
        env:
          POSTGRES_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
        run: go test ./test/integration/...
