name: test integration
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test.integration.yaml
      - "**/*.go"
      - go.mod
      - go.sum
jobs:
  integration:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Test integration
        env:
          POSTGRES_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
        run: go test ./test/integration/...
