name: vulnerability cron
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  dockle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install dockle
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/') && \
          curl -L -o dockle.deb https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb && \
          sudo dpkg -i dockle.deb && rm dockle.deb
      - name: Docker login
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Dockle vulnerability scan
        run: dockle ${{ github.repository }}:latest
  trivy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
      - name: Docker login
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Trivy vulnerability scan
        run: trivy image ${{ github.repository }}:latest
